apiVersion: skaffold/v2beta25
kind: Config
build:
  artifacts:
  - image: localhost:32000/k8sstarter
    jib:
      args:
      - -DskipTests
deploy:
  kubectl:
    manifests:
    - .infrastructure/namespace.yaml
    - .infrastructure/deployment.yaml
    - .infrastructure/service.yaml
