apiVersion: v1
kind: Service
metadata:
  namespace: microservices
  name: k8sstarter
  creationTimestamp: null
  labels:
    app: k8sstarter
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: k8sstarter
  type: ClusterIP
status:
  loadBalancer: {}
